"""Initial schema

Revision ID: 00856cadb0be
Revises: 
Create Date: 2026-02-13 23:27:40.856717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00856cadb0be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ai_usage_tenant', table_name='ai_usage_logs')
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('idx_audit_logs_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_tenant', table_name='audit_logs')
    op.drop_constraint('course_documents_course_id_fkey', 'course_documents', type_='foreignkey')
    op.create_foreign_key(None, 'course_documents', 'courses', ['course_id'], ['id'])
    op.alter_column('courses', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('idx_courses_teacher', table_name='courses')
    op.drop_index('idx_courses_tenant', table_name='courses')
    op.drop_constraint('courses_tenant_id_fkey', 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'tenants', ['tenant_id'], ['id'])
    op.drop_index('idx_enrollments_course', table_name='enrollments')
    op.drop_index('idx_enrollments_student', table_name='enrollments')
    op.drop_constraint('enrollments_course_id_fkey', 'enrollments', type_='foreignkey')
    op.drop_constraint('enrollments_student_id_fkey', 'enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'enrollments', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'enrollments', 'users', ['student_id'], ['id'])
    op.alter_column('questions', 'question_type',
               existing_type=postgresql.ENUM('mcq', 'short_answer', 'true_false', name='question_type'),
               type_=sa.Enum('MCQ', 'SHORT_ANSWER', 'TRUE_FALSE', name='questiontype'),
               existing_nullable=True,
               existing_server_default=sa.text("'mcq'::question_type"))
    op.alter_column('questions', 'difficulty',
               existing_type=postgresql.ENUM('easy', 'medium', 'hard', name='difficulty_level'),
               type_=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'::difficulty_level"))
    op.alter_column('questions', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('quiz_attempts', 'answers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('idx_quiz_attempts_quiz', table_name='quiz_attempts')
    op.drop_index('idx_quiz_attempts_student', table_name='quiz_attempts')
    op.drop_constraint('quiz_attempts_quiz_id_fkey', 'quiz_attempts', type_='foreignkey')
    op.drop_constraint('quiz_attempts_student_id_fkey', 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'])
    op.create_foreign_key(None, 'quiz_attempts', 'users', ['student_id'], ['id'])
    op.alter_column('quizzes', 'status',
               existing_type=postgresql.ENUM('draft', 'published', 'archived', name='quiz_status'),
               type_=sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='quizstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::quiz_status"))
    op.alter_column('quizzes', 'difficulty',
               existing_type=postgresql.ENUM('easy', 'medium', 'hard', name='difficulty_level'),
               type_=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'::difficulty_level"))
    op.drop_index('idx_quizzes_course', table_name='quizzes')
    op.drop_constraint('quizzes_course_id_fkey', 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'courses', ['course_id'], ['id'])
    op.alter_column('tenants', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('student', 'teacher', 'admin', 'super_admin', name='user_role'),
               type_=sa.Enum('STUDENT', 'TEACHER', 'ADMIN', 'SUPER_ADMIN', name='userrole'),
               existing_nullable=True,
               existing_server_default=sa.text("'student'::user_role"))
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_tenant', table_name='users')
    op.drop_constraint('users_tenant_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_tenant_id_fkey', 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_users_tenant', 'users', ['tenant_id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('STUDENT', 'TEACHER', 'ADMIN', 'SUPER_ADMIN', name='userrole'),
               type_=postgresql.ENUM('student', 'teacher', 'admin', 'super_admin', name='user_role'),
               existing_nullable=True,
               existing_server_default=sa.text("'student'::user_role"))
    op.alter_column('tenants', 'settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key('quizzes_course_id_fkey', 'quizzes', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_quizzes_course', 'quizzes', ['course_id'], unique=False)
    op.alter_column('quizzes', 'difficulty',
               existing_type=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'),
               type_=postgresql.ENUM('easy', 'medium', 'hard', name='difficulty_level'),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'::difficulty_level"))
    op.alter_column('quizzes', 'status',
               existing_type=sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='quizstatus'),
               type_=postgresql.ENUM('draft', 'published', 'archived', name='quiz_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::quiz_status"))
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.create_foreign_key('quiz_attempts_student_id_fkey', 'quiz_attempts', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('quiz_attempts_quiz_id_fkey', 'quiz_attempts', 'quizzes', ['quiz_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_quiz_attempts_student', 'quiz_attempts', ['student_id'], unique=False)
    op.create_index('idx_quiz_attempts_quiz', 'quiz_attempts', ['quiz_id'], unique=False)
    op.alter_column('quiz_attempts', 'answers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('questions', 'options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('questions', 'difficulty',
               existing_type=sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'),
               type_=postgresql.ENUM('easy', 'medium', 'hard', name='difficulty_level'),
               existing_nullable=True,
               existing_server_default=sa.text("'medium'::difficulty_level"))
    op.alter_column('questions', 'question_type',
               existing_type=sa.Enum('MCQ', 'SHORT_ANSWER', 'TRUE_FALSE', name='questiontype'),
               type_=postgresql.ENUM('mcq', 'short_answer', 'true_false', name='question_type'),
               existing_nullable=True,
               existing_server_default=sa.text("'mcq'::question_type"))
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.create_foreign_key('enrollments_student_id_fkey', 'enrollments', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('enrollments_course_id_fkey', 'enrollments', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_enrollments_student', 'enrollments', ['student_id'], unique=False)
    op.create_index('idx_enrollments_course', 'enrollments', ['course_id'], unique=False)
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key('courses_tenant_id_fkey', 'courses', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_courses_tenant', 'courses', ['tenant_id'], unique=False)
    op.create_index('idx_courses_teacher', 'courses', ['teacher_id'], unique=False)
    op.alter_column('courses', 'settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(None, 'course_documents', type_='foreignkey')
    op.create_foreign_key('course_documents_course_id_fkey', 'course_documents', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_audit_logs_tenant', 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('idx_audit_logs_created', 'audit_logs', ['created_at'], unique=False)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_index('idx_ai_usage_tenant', 'ai_usage_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
